### PR TITLE
refactor(all): move to sass & javascript oriented accent picking

### LINKED ISSUE #47: Marketplace
Can we not flood the marketplace with each color scheme? Color.inis exist for a reason and are directly compatible with marketplace, there is no reason to have 5 different extensions for the same theme.

### PR DESCRIPTION
**Pull request by ohitstom**
resolves #47

This will affect how users contribute heavily, whilst 100% a positive since sass/scss improves the workflow a tonne and allows cleaner code thats easier to audit, it can put a barrier in place for lower level users to make PRs.

However i believe this PR will have a positive impact overall in people wanting to contribute since (no offense) but you can actually read how it works without jumping back and forward between 50 files 🦖 

side note: wow that react is fast, its literally instantaneous.... 

+ marketplace support for the equalizer theming through remote loading

### CODE REVIEW

**Comment by ghostx31** [comment]
> However i believe this PR will have a positive impact overall in people wanting to contribute since (no offense) but you can actually read how it works without jumping back and forward between 50 files 🦖

Completely agreed (I am at fault too there, tbh haha)
We'll have someone test this out in a bit, especially on Windows and once its in the clear, we'll get this merged. Thanks for the PR!

**Comment by PoorPocketsMcNewHold** [comment]
LGTM on Solus Linux, via the “Native Linux” version (Not Snap/Flatpak).

**Review by PoorPocketsMcNewHold — APPROVED** [review]
LGTM on Solus Linux, via the “Native Linux” version (Not Snap/Flatpak).

**Review by coldenate — APPROVED** [review]
Looks and works great on MacOS M1! Nice job!!

**Pull request merged**
