### PR TITLE
resolves #51

### LINKED ISSUE #51: Playlist Play/Pause Icon Margin (top bar upon scroll)
image
Playlist play icon upon scroll needs some margin-right, or the text

### PR DESCRIPTION
**Pull request by ohitstom**
resolves #51

### CODE REVIEW

**Comment by ohitstom** [comment]
@isabelroses

**Comment by isabelroses** [comment]
> @isabelroses

Hey Tom why have you mentioned me?

**Comment by ohitstom** [comment]
> > @isabelroses
> 
> Hey Tom why have you mentioned me?

I do not have write access to this repo and thought you did!

**Comment by isabelroses** [comment]
> I do not have write access to this repo and thought you did!
> my apologies if you dont

No, sorry I don't.

**Pull request merged**
