### PR TITLE
feat/fix: add missing sapphire accent

### PR DESCRIPTION
**Pull request by anuragxone**
i tried to add missing sapphire accent which was missing before, can any maintainer guide me here, i'm kinda new to this stuff, @ohitstom ?

### CODE REVIEW

**Comment by ohitstom** [comment]
looks fine to me, not tested it though.
Since when was sapphire a part of the palette though?

**Comment by anuragxone** [comment]
> looks fine to me, not tested it though. Since when was sapphire a part of the palette though?

i kinda don't know when, but i was just applying the theme system wide, and discovered that sapphire was missing, if you approve this change can you put hacktoberfest-accepted label on this, it'll help me a lot

**Comment by ohitstom** [comment]
> > looks fine to me, not tested it though. Since when was sapphire a part of the palette though?
> 
> i kinda don't know when, but i was just applying the theme system wide, and discovered that sapphire was missing, if you approve this change can you put hacktoberfest-accepted label on this, it'll help me a lot

im currently not in great standing with the team and don't have explicit org permissions to do this. However this PR gets an unofficial approval from me, @pocco81 should be able to help you out with the hacktoberfest stuff and merging :)

**Comment by anuragxone** [comment]
> > > looks fine to me, not tested it though. Since when was sapphire a part of the palette though?
> > 
> > 
> > i kinda don't know when, but i was just applying the theme system wide, and discovered that sapphire was missing, if you approve this change can you put hacktoberfest-accepted label on this, it'll help me a lot
> 
> im currently not in great standing with the team and don't have explicit org permissions to do this. However this PR gets an unofficial approval from me, @pocco81 should be able to help you out with the hacktoberfest stuff and merging :)

oh okay, @davidbgonz ?

**Comment by davidbgonz** [comment]
Lgtm

**Comment by davidbgonz** [comment]
Thanks for catching that @anuragxone

**Pull request merged**
